package mx.cacho.choice.soapws.client;

import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;

import javax.xml.namespace.QName;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 */
@WebServiceClient(name = "ChoicePortService", targetNamespace = "http://choice.cacho.mx/soap-ws/hotels", wsdlLocation = "http://localhost:18080/ws/choice.wsdl")
public class ChoicePortService
        extends Service {

    private final static URL CHOICEPORTSERVICE_WSDL_LOCATION;
    private final static WebServiceException CHOICEPORTSERVICE_EXCEPTION;
    private final static QName CHOICEPORTSERVICE_QNAME = new QName("http://choice.cacho.mx/soap-ws/hotels", "ChoicePortService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:18080/ws/choice.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CHOICEPORTSERVICE_WSDL_LOCATION = url;
        CHOICEPORTSERVICE_EXCEPTION = e;
    }

    public ChoicePortService() {
        super(__getWsdlLocation(), CHOICEPORTSERVICE_QNAME);
    }

    public ChoicePortService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CHOICEPORTSERVICE_QNAME, features);
    }

    public ChoicePortService(URL wsdlLocation) {
        super(wsdlLocation, CHOICEPORTSERVICE_QNAME);
    }

    public ChoicePortService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CHOICEPORTSERVICE_QNAME, features);
    }

    public ChoicePortService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ChoicePortService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    private static URL __getWsdlLocation() {
        if (CHOICEPORTSERVICE_EXCEPTION != null) {
            throw CHOICEPORTSERVICE_EXCEPTION;
        }
        return CHOICEPORTSERVICE_WSDL_LOCATION;
    }

    /**
     * @return returns ChoicePort
     */
    @WebEndpoint(name = "ChoicePortSoap11")
    public ChoicePort getChoicePortSoap11() {
        return super.getPort(new QName("http://choice.cacho.mx/soap-ws/hotels", "ChoicePortSoap11"), ChoicePort.class);
    }

    /**
     * @param features A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns ChoicePort
     */
    @WebEndpoint(name = "ChoicePortSoap11")
    public ChoicePort getChoicePortSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("http://choice.cacho.mx/soap-ws/hotels", "ChoicePortSoap11"), ChoicePort.class, features);
    }

}
